language: python
sudo: false
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install coverage
  - pip install coveralls
# command to run tests
script: travis_run.sh
after_success: coveralls